# Generated by Django 4.2.2 on 2023-07-21 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='史跡名')),
                ('lat', models.FloatField(verbose_name='緯度')),
                ('lng', models.FloatField(verbose_name='経度')),
                ('description', models.TextField(verbose_name='場所の説明')),
                ('relation', models.CharField(max_length=20, verbose_name='関連人物名')),
            ],
            options={
                'verbose_name': '史跡',
            },
        ),
    ]
